// 词汇卡片 - 默认词库数据
// 从主 HTML 文件中抽离，便于独立维护和扩展
window.DEFAULT_WORDS = {
    '数字': [
        { word: '一', en: 'one', en_chunks: ['o','ne'], emoji: '1', isNumber: true },
        { word: '二', en: 'two', en_chunks: ['t','wo'], emoji: '2', isNumber: true },
        { word: '三', en: 'three', en_chunks: ['th','ree'], emoji: '3', isNumber: true },
        { word: '四', en: 'four', en_chunks: ['f','our'], emoji: '4', isNumber: true },
        { word: '五', en: 'five', en_chunks: ['f','ive'], emoji: '5', isNumber: true },
        { word: '六', en: 'six', en_chunks: ['s','ix'], emoji: '6', isNumber: true },
        { word: '七', en: 'seven', en_chunks: ['se','ven'], emoji: '7', isNumber: true },
        { word: '八', en: 'eight', en_chunks: ['e','ight'], emoji: '8', isNumber: true },
        { word: '九', en: 'nine', en_chunks: ['n','ine'], emoji: '9', isNumber: true },
        { word: '十', en: 'ten', en_chunks: ['t','en'], emoji: '10', isNumber: true }
    ],
    '水果': [
        { word: '苹果', en: 'apple', en_chunks: ['ap','ple'], emoji: '🍎' },
        { word: '香蕉', en: 'banana', en_chunks: ['ba','na','na'], emoji: '🍌' },
        { word: '葡萄', en: 'grape', en_chunks: ['gr','ape'], emoji: '🍇' },
        { word: '草莓', en: 'strawberry', en_chunks: ['straw','ber','ry'], emoji: '🍓' },
        { word: '橙子', en: 'orange', en_chunks: ['or','ange'], emoji: '🍊' },
        { word: '西瓜', en: 'watermelon', en_chunks: ['wa','ter','mel','on'], emoji: '🍉' },
        { word: '桃子', en: 'peach', en_chunks: ['p','each'], emoji: '🍑' },
        { word: '梨', en: 'pear', en_chunks: ['p','ear'], emoji: '🍐' },
        { word: '樱桃', en: 'cherry', en_chunks: ['cher','ry'], emoji: '🍒' },
        { word: '柠檬', en: 'lemon', en_chunks: ['lem','on'], emoji: '🍋' },
        { word: '芒果', en: 'mango', en_chunks: ['man','go'], emoji: '🥭' },
        { word: '菠萝', en: 'pineapple', en_chunks: ['pine','ap','ple'], emoji: '🍍' },
        { word: '猕猴桃', en: 'kiwi', en_chunks: ['ki','wi'], emoji: '🥝' }
    ],
    '动物': [
        { word: '猫', en: 'cat', en_chunks: ['c','at'], emoji: '🐱' },
        { word: '狗', en: 'dog', en_chunks: ['d','og'], emoji: '🐶' },
        { word: '鸟', en: 'bird', en_chunks: ['b','ird'], emoji: '🐦' },
        { word: '鱼', en: 'fish', en_chunks: ['f','ish'], emoji: '🐟' },
        { word: '兔子', en: 'rabbit', en_chunks: ['rab','bit'], emoji: '🐰' },
        { word: '大象', en: 'elephant', en_chunks: ['el','e','phant'], emoji: '🐘' },
        { word: '老虎', en: 'tiger', en_chunks: ['ti','ger'], emoji: '🐯' },
        { word: '狮子', en: 'lion', en_chunks: ['li','on'], emoji: '🦁' },
        { word: '长颈鹿', en: 'giraffe', en_chunks: ['gi','raffe'], emoji: '🦒' },
        { word: '猴子', en: 'monkey', en_chunks: ['mon','key'], emoji: '🐒' },
        { word: '熊', en: 'bear', en_chunks: ['b','ear'], emoji: '🐻' },
        { word: '熊猫', en: 'panda', en_chunks: ['pan','da'], emoji: '🐼' },
        { word: '猪', en: 'pig', en_chunks: ['p','ig'], emoji: '🐷' },
        { word: '牛', en: 'cow', en_chunks: ['c','ow'], emoji: '🐮' },
        { word: '羊', en: 'sheep', en_chunks: ['sh','eep'], emoji: '🐑' },
        { word: '马', en: 'horse', en_chunks: ['h','orse'], emoji: '🐴' },
        { word: '青蛙', en: 'frog', en_chunks: ['fr','og'], emoji: '🐸' },
        { word: '鸭子', en: 'duck', en_chunks: ['d','uck'], emoji: '🦆' },
        { word: '鸡', en: 'chicken', en_chunks: ['chick','en'], emoji: '🐔' },
        { word: '蝴蝶', en: 'butterfly', en_chunks: ['but','ter','fly'], emoji: '🦋' },
        { word: '瓢虫', en: 'ladybug', en_chunks: ['la','dy','bug'], emoji: '🐞' },
        { word: '蜘蛛', en: 'spider', en_chunks: ['spi','der'], emoji: '🕷️' },
        { word: '蜜蜂', en: 'bee', en_chunks: ['b','ee'], emoji: '🐝' },
        { word: '苍蝇', en: 'fly', en_chunks: ['f','ly'], emoji: '🪰' },
        { word: '海豚', en: 'dolphin', en_chunks: ['dol','phin'], emoji: '🐬' },
        { word: '鲸鱼', en: 'whale', en_chunks: ['wh','ale'], emoji: '🐋' }
    ],
    '交通工具': [
        { word: '火车', en: 'train', en_chunks: ['tr','ain'], emoji: '🚂' },
        { word: '飞机', en: 'airplane', en_chunks: ['air','plane'], emoji: '✈️' },
        { word: '轮船', en: 'ship', en_chunks: ['sh','ip'], emoji: '🚢' },
        { word: '汽车', en: 'car', en_chunks: ['c','ar'], emoji: '🚗' },
        { word: '自行车', en: 'bicycle', en_chunks: ['bi','cy','cle'], emoji: '🚲' },
        { word: '公交车', en: 'bus', en_chunks: ['b','us'], emoji: '🚌' },
        { word: '出租车', en: 'taxi', en_chunks: ['tax','i'], emoji: '🚕' },
        { word: '救护车', en: 'ambulance', en_chunks: ['am','bu','lance'], emoji: '🚑' },
        { word: '消防车', en: 'firetruck', en_chunks: ['fire','truck'], emoji: '🚒' },
        { word: '警车', en: 'police car', en_chunks: ['po','lice','car'], emoji: '🚓' },
        { word: '摩托车', en: 'motorcycle', en_chunks: ['mo','tor','cy','cle'], emoji: '🏍️' },
        { word: '火箭', en: 'rocket', en_chunks: ['rock','et'], emoji: '🚀' },
        { word: '直升机', en: 'helicopter', en_chunks: ['hel','i','cop','ter'], emoji: '🚁' },
        { word: '拖拉机', en: 'tractor', en_chunks: ['trac','tor'], emoji: '🚜' },
        { word: '帆船', en: 'sailboat', en_chunks: ['sail','boat'], emoji: '⛵' }
    ],
    '食物': [
        { word: '面包', en: 'bread', en_chunks: ['br','ead'], emoji: '🍞' },
        { word: '蛋糕', en: 'cake', en_chunks: ['c','ake'], emoji: '🍰' },
        { word: '饼干', en: 'cookie', en_chunks: ['cook','ie'], emoji: '🍪' },
        { word: '披萨', en: 'pizza', en_chunks: ['piz','za'], emoji: '🍕' },
        { word: '汉堡', en: 'hamburger', en_chunks: ['ham','bur','ger'], emoji: '🍔' },
        { word: '薯条', en: 'fries', en_chunks: ['fr','ies'], emoji: '🍟' },
        { word: '面条', en: 'noodles', en_chunks: ['noo','dles'], emoji: '🍜' },
        { word: '米饭', en: 'rice', en_chunks: ['r','ice'], emoji: '🍚' },
        { word: '饺子', en: 'dumpling', en_chunks: ['dump','ling'], emoji: '🥟' },
        { word: '鸡蛋', en: 'egg', en_chunks: ['e','gg'], emoji: '🥚' },
        { word: '牛奶', en: 'milk', en_chunks: ['m','ilk'], emoji: '🥛' },
        { word: '鸡腿', en: 'chicken leg', en_chunks: ['chick','en','leg'], emoji: '🍗' },
        { word: '冰淇淋', en: 'ice cream', en_chunks: ['ice','cream'], emoji: '🍦' },
        { word: '巧克力', en: 'chocolate', en_chunks: ['choc','o','late'], emoji: '🍫' },
        { word: '爆米花', en: 'popcorn', en_chunks: ['pop','corn'], emoji: '🍿' },
        { word: '寿司', en: 'sushi', en_chunks: ['su','shi'], emoji: '🍣' },
        { word: '幸运饼干', en: 'fortune cookie', en_chunks: ['fortune','cookie'], emoji: '🥠' }
    ],
    '玩具': [
        { word: '滑梯', en: 'slide', en_chunks: ['sl','ide'], emoji: '🛝' },
        { word: '气球', en: 'balloon', en_chunks: ['bal','loon'], emoji: '🎈' },
        { word: '泰迪熊', en: 'teddy bear', en_chunks: ['teddy','bear'], emoji: '🧸' },
        { word: '溜溜球', en: 'yo-yo', en_chunks: ['yo-','yo'], emoji: '🪀' },
        { word: '礼物', en: 'gift', en_chunks: ['g','ift'], emoji: '🎁' }
    ],
    '颜色': [
        { word: '红色', en: 'red', en_chunks: ['r','ed'], emoji: '🔴' },
        { word: '蓝色', en: 'blue', en_chunks: ['bl','ue'], emoji: '🔵' },
        { word: '绿色', en: 'green', en_chunks: ['gr','een'], emoji: '🟢' },
        { word: '黄色', en: 'yellow', en_chunks: ['yel','low'], emoji: '🟡' },
        { word: '橙色', en: 'orange', en_chunks: ['or','ange'], emoji: '🟠' },
        { word: '紫色', en: 'purple', en_chunks: ['pur','ple'], emoji: '🟣' },
        { word: '黑色', en: 'black', en_chunks: ['bl','ack'], emoji: '⚫' },
        { word: '白色', en: 'white', en_chunks: ['wh','ite'], emoji: '⚪' },
        { word: '粉色', en: 'pink', en_chunks: ['p','ink'], emoji: '💗' },
        { word: '棕色', en: 'brown', en_chunks: ['br','own'], emoji: '🟤' }
    ],
    '天气': [
        { word: '太阳', en: 'sun', en_chunks: ['s','un'], emoji: '☀️' },
        { word: '月亮', en: 'moon', en_chunks: ['m','oon'], emoji: '🌙' },
        { word: '星星', en: 'star', en_chunks: ['st','ar'], emoji: '⭐' },
        { word: '云', en: 'cloud', en_chunks: ['cl','oud'], emoji: '☁️' },
        { word: '雨', en: 'rain', en_chunks: ['r','ain'], emoji: '🌧️' },
        { word: '雪', en: 'snow', en_chunks: ['sn','ow'], emoji: '❄️' },
        { word: '风', en: 'wind', en_chunks: ['w','ind'], emoji: '💨' },
        { word: '彩虹', en: 'rainbow', en_chunks: ['rain','bow'], emoji: '🌈' },
        { word: '闪电', en: 'lightning', en_chunks: ['light','ning'], emoji: '⚡' },
        { word: '雾', en: 'fog', en_chunks: ['f','og'], emoji: '🌫️' }
    ],
    '家庭成员': [
        { word: '爸爸', en: 'dad', en_chunks: ['d','ad'], emoji: '👨' },
        { word: '妈妈', en: 'mom', en_chunks: ['m','om'], emoji: '👩' },
        { word: '哥哥', en: 'big brother', en_chunks: ['big','brother'], emoji: '👦' },
        { word: '姐姐', en: 'big sister', en_chunks: ['big','sister'], emoji: '👧' },
        { word: '弟弟', en: 'little brother', en_chunks: ['little','brother'], emoji: '👶' },
        { word: '妹妹', en: 'little sister', en_chunks: ['little','sister'], emoji: '👧' },
        { word: '爷爷', en: 'grandpa', en_chunks: ['grand','pa'], emoji: '👴' },
        { word: '奶奶', en: 'grandma', en_chunks: ['grand','ma'], emoji: '👵' },
        { word: '叔叔', en: 'uncle', en_chunks: ['un','cle'], emoji: '🧔' },
        { word: '阿姨', en: 'aunt', en_chunks: ['aunt'], emoji: '👩\u200d🦰' }
    ],
    '形状': [
        { word: '圆形', en: 'circle', en_chunks: ['cir','cle'], emoji: '⚪' },
        { word: '正方形', en: 'square', en_chunks: ['s','quare'], emoji: '⬜' },
        { word: '三角形', en: 'triangle', en_chunks: ['tri','an','gle'], emoji: '🔺' },
        { word: '星形', en: 'star', en_chunks: ['st','ar'], emoji: '⭐' },
        { word: '心形', en: 'heart', en_chunks: ['h','eart'], emoji: '❤️' },
        { word: '菱形', en: 'diamond', en_chunks: ['di','a','mond'], emoji: '🔷' },
        { word: '十字形', en: 'cross', en_chunks: ['cr','oss'], emoji: '➕' }
    ],
    '动作': [
        { word: '跑步', en: 'run', en_chunks: ['r','un'], emoji: '🏃' },
        { word: '走路', en: 'walk', en_chunks: ['w','alk'], emoji: '🚶' },
        { word: '站立', en: 'stand', en_chunks: ['st','and'], emoji: '🧍' },
        { word: '坐下', en: 'sit', en_chunks: ['s','it'], emoji: '🪑' },
        { word: '睡觉', en: 'sleep', en_chunks: ['sl','eep'], emoji: '😴' },
        { word: '大笑', en: 'laugh', en_chunks: ['l','augh'], emoji: '😄' },
        { word: '哭泣', en: 'cry', en_chunks: ['cr','y'], emoji: '😢' },
        { word: '拍手', en: 'clap', en_chunks: ['cl','ap'], emoji: '👏' },
        { word: '挥手', en: 'wave', en_chunks: ['w','ave'], emoji: '👋' },
        { word: '拥抱', en: 'hug', en_chunks: ['h','ug'], emoji: '🤗' },
        { word: '唱歌', en: 'sing', en_chunks: ['s','ing'], emoji: '🎤' },
        { word: '跳舞', en: 'dance', en_chunks: ['d','ance'], emoji: '💃' }
    ],
    '场景': [
        { word: '学校', en: 'school', en_chunks: ['sch','ool'], emoji: '🏫' },
        { word: '河流', en: 'river', en_chunks: ['riv','er'], emoji: '🏞️' },
        { word: '高山', en: 'mountain', en_chunks: ['moun','tain'], emoji: '⛰️' },
        { word: '农田', en: 'farm', en_chunks: ['f','arm'], emoji: '🌾' },
        { word: '海滩', en: 'beach', en_chunks: ['b','each'], emoji: '🏖️' }
    ]
};
